site_name: FJFormer

nav:
  - Home: index.md
  - Attention:
    - Flash Attention 0: fjformer-attention-flash_attention_0.md
    - Jax Flash Attn Tpu: fjformer-attention-jax_flash_attn_tpu.md
    - Flash Attention: fjformer-attention-flash_attention.md
    - Jax Flash Attn Gpu: fjformer-attention-jax_flash_attn_gpu.md
    - Flash Attention Tpu: fjformer-attention-flash_attention_tpu.md
    - Efficient Attention: fjformer-attention-efficient_attention.md
    - Flash Attention Gpu: fjformer-attention-flash_attention_gpu.md
  - Partition Utils:
    - Mesh Utils: fjformer-partition_utils-mesh_utils.md
    - T5X Partitioning: fjformer-partition_utils-t5x_partitioning.md
  - GPU Pallas:
    - Softmax: fjformer-gpu_pallas-softmax.md
    - Layer Norm: fjformer-gpu_pallas-layer_norm.md
    - Attention: fjformer-gpu_pallas-attention.md
    - Rms Norm: fjformer-gpu_pallas-rms_norm.md
  - BITS:
    - Q Dot General: fjformer-bits-q_dot_general.md
    - Config: fjformer-bits-config.md
    - Bits: fjformer-bits-bits.md
    - Q flax: fjformer-bits-q_flax.md
    - Calibration: fjformer-bits-calibration.md
    - Stochastic Rounding: fjformer-bits-stochastic_rounding.md
    - Int Numerics: fjformer-bits-int_numerics.md
  - Func:
    - loss_func: fjformer-func-loss_func.md
    - _func: fjformer-func-_func.md
  - Load:
    - streamer: fjformer-load-streamer.md
    - _load: fjformer-load-_load.md
  - Optimizers:
    - adamw: fjformer-optimizers-adamw.md
    - lion: fjformer-optimizers-lion.md
    - optimizer_utils: fjformer-optimizers-optimizer_utils.md
    - adafactor: fjformer-optimizers-adafactor.md
  - Datasets:
    - datasets: fjformer-datasets-datasets.md
  - Monitor:
    - tracker: fjformer-monitor-tracker.md
  - Utils:
    - Utils: fjformer-utils.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python

copyright: "Erfan Zare Chavoshi-FJFormer"

site_author: "Erfan Zare Chavoshi"