site_name: FJFormer

nav:
  - Home: index.md
  - fjformer/attention/flash_attention_0: fjformer-attention-flash_attention_0.md
  - fjformer/attention/jax_flash_attn_tpu: fjformer-attention-jax_flash_attn_tpu.md
  - fjformer/attention/flash_attention: fjformer-attention-flash_attention.md
  - fjformer/attention/jax_flash_attn_gpu: fjformer-attention-jax_flash_attn_gpu.md
  - fjformer/attention/flash_attention_tpu: fjformer-attention-flash_attention_tpu.md
  - fjformer/attention/efficient_attention: fjformer-attention-efficient_attention.md
  - fjformer/attention/flash_attention_gpu: fjformer-attention-flash_attention_gpu.md
  - fjformer/partition_utils/mesh_utils: fjformer-partition_utils-mesh_utils.md
  - fjformer/partition_utils/t5x_partitioning: fjformer-partition_utils-t5x_partitioning.md
  - fjformer/gpu_pallas/softmax: fjformer-gpu_pallas-softmax.md
  - fjformer/gpu_pallas/layer_norm: fjformer-gpu_pallas-layer_norm.md
  - fjformer/gpu_pallas/attention: fjformer-gpu_pallas-attention.md
  - fjformer/gpu_pallas/rms_norm: fjformer-gpu_pallas-rms_norm.md
  - fjformer/bits/q_dot_general: fjformer-bits-q_dot_general.md
  - fjformer/bits/config: fjformer-bits-config.md
  - fjformer/bits/bits: fjformer-bits-bits.md
  - fjformer/bits/q_flax: fjformer-bits-q_flax.md
  - fjformer/bits/calibration: fjformer-bits-calibration.md
  - fjformer/bits/stochastic_rounding: fjformer-bits-stochastic_rounding.md
  - fjformer/bits/int_numerics: fjformer-bits-int_numerics.md
  - fjformer/func/loss_func: fjformer-func-loss_func.md
  - fjformer/func/_func: fjformer-func-_func.md
  - fjformer/load/streamer: fjformer-load-streamer.md
  - fjformer/load/_load: fjformer-load-_load.md
  - fjformer/optimizers/adamw: fjformer-optimizers-adamw.md
  - fjformer/optimizers/lion: fjformer-optimizers-lion.md
  - fjformer/optimizers/optimizer_utils: fjformer-optimizers-optimizer_utils.md
  - fjformer/optimizers/adafactor: fjformer-optimizers-adafactor.md
  - fjformer/datasets/datasets: fjformer-datasets-datasets.md
  - fjformer/monitor/tracker: fjformer-monitor-tracker.md
  - fjformer/utils: fjformer-utils.md
plugins:
  - search
  - mkdocstrings

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python