site_name: FJFormer

nav:
  - Home: index.md
  - FlashAttention:
      - Flash attention 0: fjformer-attention-flash_attention_0.md
      - Jax flash attn tpu: fjformer-attention-jax_flash_attn_tpu.md
      - Flash attention: fjformer-attention-flash_attention.md
      - Jax flash attn gpu: fjformer-attention-jax_flash_attn_gpu.md
      - Flash attention tpu: fjformer-attention-flash_attention_tpu.md
      - Efficient attention: fjformer-attention-efficient_attention.md
      - Flash attention gpu: fjformer-attention-flash_attention_gpu.md
  - Partition utils:
      - mesh utils: fjformer-partition_utils-mesh_utils.md
      - t5x partitioning: fjformer-partition_utils-t5x_partitioning.md
  - Checkpoint:
      - streamer: fjformer-checkpoint-streamer.md
      - load: fjformer-checkpoint-_load.md
  - GPU Pallas:
      - softmax: fjformer-gpu_pallas-softmax.md
      - layer norm: fjformer-gpu_pallas-layer_norm.md
      - attention: fjformer-gpu_pallas-attention.md
      - rms norm: fjformer-gpu_pallas-rms_norm.md
  - Bits:
      - q dot general: fjformer-bits-q_dot_general.md
      - config: fjformer-bits-config.md
      - no numerics: fjformer-bits-no_numerics.md
      - bits: fjformer-bits-bits.md
      - q flax: fjformer-bits-q_flax.md
      - calibration: fjformer-bits-calibration.md
      - stochastic rounding: fjformer-bits-stochastic_rounding.md
      - numerics: fjformer-bits-numerics.md
      - int numerics: fjformer-bits-int_numerics.md
  - func:
      - loss func: fjformer-func-loss_func.md
      - _func: fjformer-func-_func.md
  - Optimizers:
      - Adamw: fjformer-optimizers-adamw.md
      - Lion: fjformer-optimizers-lion.md
      - Optimizer utils: fjformer-optimizers-optimizer_utils.md
      - Adafactor: fjformer-optimizers-adafactor.md
  - Datasets:
      - datasets: fjformer-datasets-datasets.md
  - Monitor:
      - Tracker: fjformer-monitor-tracker.md
  - Utils: fjformer-utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python

copyright: "Erfan Zare Chavoshi-FJFormer"

site_author: "Erfan Zare Chavoshi"